CREATE DATABASE TASK2
USE TASK2

CREATE TABLE Roles(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR (50) UNIQUE NOT NULL)

CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY,
Username VARCHAR(40) UNIQUE NOT NULL,
Password VARCHAR(30),
RoleId INT NOT NULL,
FOREIGN KEY (RoleId) REFERENCES Roles(Id)
)

SELECT Users.Username,Roles.Name
FROM Users
JOIN Roles
ON Users.RoleId = Roles.Id
